# This will publish the actual server code.
# Think twice if you really need this

name: 'Publish server package'

on:
  workflow_call:
    inputs:
      node-version:
        description: 'node version to use'
        type: string
        default: '14'

env:
  GITHUB_PACKAGES_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  publish-server:
    name: 'publish-server'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v3'
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
      - name: 'npm install'
        run: npm ci
      - name: 'run build'
        run: 'npm run build'
      - name: 'run publish'
        run: 'npm publish'

