name: 'Run Tests'

on:
  workflow_call:
    inputs:
      node-version:
        description: 'node version to use'
        type: string
        default: '14'

  
env:
  GITHUB_PACKAGES_TOKEN: ${{ secrets.RETRAIN_PACKAGES_TOKEN }}
  CI: true
jobs:
  run-tests:
    name: 'Run all tests'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.ref }}
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v3'
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
      - name: 'npm install'
        run: npm ci
      - name: 'build typescript'
        run: npm run build:tsc --if-present
      - name: 'npm run test'
        run: npm run test