name: 'Run Tests'

on:
  workflow_call:
    inputs:
      python-version:
        description: 'python version to use'
        type: string
        default: '3.9'
      min-coverage:
        description: 'minimum coverage'
        type: number
        default: 0.8

env:
  GCP_ARTIFACT_REGISTRY_KEY: ${{ secrets.GCP_ARTIFACT_REGISTRY_KEY }}

jobs:
  run-tests:
    name: 'Run tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
      - name: 'Setup Python'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          architecture: 'x64'
      - name: 'pip install'
        run: pip install --extra-index-url=https://_json_key_base64:$GCP_ARTIFACT_REGISTRY_KEY@europe-west4-python.pkg.dev/retrain-utils/retrain-pypi/simple/ -r requirements.txt
      - name: 'unit tests with pytest'
        run: |
          coverage run -m pytest tests/unit_tests; coverage xml
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-xml
          path: coverage.xml
  coverage-report:
    name: 'Coverage report'
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: coverage-xml
      - name: 'Coverage report'
        uses: orgoro/coverage@v3
        with:
            coverageFile: coverage.xml
            thresholdAll: ${{ inputs.min-coverage }}
            token: ${{ secrets.GITHUB_TOKEN }}