name: 'Publish package'

on:
  workflow_call:
    inputs:
      python-version:
        description: 'python version to use'
        type: string
        default: '3.9'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
        - name: 'Checkout source code'
          uses: 'actions/checkout@v3'
        - name: 'Setup Python'
          uses: actions/setup-python@v4
          with:
            python-version: ${{ inputs.python-version }}
            architecture: 'x64'
        - name: Install dependencies
          run: pip install setuptools wheel twine keyring keyrings.google-artifactregistry-auth
        - name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v0'
          with:
            credentials_json: '${{ secrets.GCP_ARTIFACT_REGISTRY_KEY }}'
        - name: Build and publish
          run: |
            python setup.py sdist bdist_wheel
            twine upload --skip-existing --verbose --repository-url https://europe-west4-python.pkg.dev/retrain-utils/retrain-pypi/ dist/* || /usr/bin/true